import Head from "next/head";
import Link from "next/link";
import { PageData } from "@/types/data";
import Crypto from "@/components/Crypto";
import CryptoStatistics from "@/components/CryptoStatistics";
import { useSession } from "next-auth/react";
import { getCryptosData } from "@/services/apiService";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home({ cryptoData }: PageData.IndexPageData) {
  const { data: session, status } = useSession();
  return (
    <>
      <Head>
        <title>CryptoVault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-auto p-6">
        <section>
          <h1 className="mb-5 text-2xl">Crypto Market Statistics</h1>
          <CryptoStatistics cryptoData={cryptoData} />
        </section>
        <section className="mt-10">
          <h1 className="mb-5 text-2xl">Top 10 Crypto</h1>
          <Crypto cryptoData={cryptoData} />
          <div className="my-8 text-center">
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r">
              <Link href="/coins">Load More</Link>
            </button>
          </div>
        </section>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const limit = "10";
  const cryptoData = await getCryptosData(limit);
  return {
    props: {
      cryptoData,
    },
  };
};
