import Head from "next/head";
import { GetServerSideProps } from "next";
import { PageData } from "@/types/data";
import CryptoStatistics from "@/components/CryptoStatistics";
import Crypto from "@/components/Crypto";
import NavBar from "@/components/shared/NavBar";

export default function Home({ cryptoData }: PageData.IndexPageData) {
  return (
    <>
      <Head>
        <title>CryptoVault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main className="container m-auto p-6">
        <section>
          <h1 className="mb-5 text-2xl">Crypto Market Statistics</h1>
          <CryptoStatistics cryptoData={cryptoData} />
        </section>
        <section className="mt-10">
          <h1 className="mb-5 text-2xl">Top 10 Crypto</h1>
          <Crypto cryptoData={cryptoData} />
        </section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const referenceCurrencyUuid = 'yhjMzLPhuIDl';
  const limit = '10';
  const response = await fetch(
    `https://coinranking1.p.rapidapi.com/coins?referenceCurrencyUuid=${referenceCurrencyUuid}&limit=${limit}`,
    {
      headers: {
        "x-rapidapi-key": `${process.env.NEXT_PUBLIC_RAPID_API_KEY}`,
        "x-rapidapi-host": `${process.env.NEXT_PUBLIC_RAPID_API_HOST}`,
      },
    }
  );
  const cryptoData = await response.json();
  return {
    props: {
      cryptoData
    },
  };
};
